-- 第5週: 旅行プランの表を作り、今のダミーデータを入れる
-- Supabase の「SQL Editor」にこのファイルの中身を全部貼り付けて「Run」を押します。

-- プランの表（Excel のシートのようなもの）
create table public.plans (
  id          bigint generated by default as identity primary key,
  title       text    not null,
  area        text    not null,
  destination text    not null,
  latitude    double precision not null,
  longitude   double precision not null,
  days        integer not null check (days > 0),
  price       integer not null check (price >= 0),
  summary     text    not null default '',
  highlights  text[]  not null default '{}',
  created_at  timestamptz not null default now()
);

-- RLS（行ごとのアクセス制限）をオンにする。オンにすると、下で許可したことしかできなくなる
alter table public.plans enable row level security;

-- 許可1: サイトを見に来た人は誰でも、プランを「見る」ことだけできる
create policy "誰でもプランを見られる"
  on public.plans for select
  to anon, authenticated
  using (true);

grant select on public.plans to anon, authenticated;

-- ダミーデータ（data/plans.json と同じ内容）
insert into public.plans (title, area, destination, latitude, longitude, days, price, summary, highlights) values
  ('古都をゆっくり歩く 京都2泊3日', '関西', '京都', 35.0116, 135.7681, 3, 48000,
   '朝の伏見稲荷と夕方の祇園。混雑を避けた時間帯で名所をめぐります。',
   array['伏見稲荷大社', '嵐山の竹林', '祇園の町家で夕食']),
  ('海と島めぐり 沖縄3泊4日', '沖縄', '那覇', 26.2124, 127.6809, 4, 89000,
   '本島から離島へ。シュノーケリングと島の食堂をめぐる旅です。',
   array['慶良間諸島でシュノーケリング', '首里城公園', '国際通りの屋台']),
  ('雪と温泉 札幌・小樽2泊3日', '北海道', '札幌', 43.0618, 141.3545, 3, 62000,
   '冬の運河と定山渓温泉。海鮮市場の朝ごはん付きです。',
   array['小樽運河', '定山渓温泉', '二条市場の海鮮丼']),
  ('週末で行ける 箱根1泊2日', '関東', '箱根', 35.2324, 139.1069, 2, 32000,
   'ロープウェイと芦ノ湖の遊覧船。都心から近い温泉の定番コースです。',
   array['大涌谷', '芦ノ湖の海賊船', '彫刻の森美術館']),
  ('城下町と現代アート 金沢2泊3日', '北陸', '金沢', 36.5613, 136.6562, 3, 54000,
   '兼六園とひがし茶屋街に、21世紀美術館を組み合わせたプランです。',
   array['兼六園', 'ひがし茶屋街', '金沢21世紀美術館']),
  ('屋久島 森歩き3泊4日', '九州', '屋久島', 30.3586, 130.5287, 4, 98000,
   'ガイドと歩く白谷雲水峡。体力に合わせてコースを選べます。',
   array['白谷雲水峡', '千尋の滝', '島の温泉']);
