-- 第6週: 問い合わせを保存する表を作る
-- Supabase の「SQL Editor」にこのファイルの中身を全部貼り付けて「Run」を押します。

create table public.inquiries (
  id         bigint generated by default as identity primary key,
  plan_id    bigint references public.plans (id) on delete set null,
  name       text not null check (char_length(name) between 1 and 100),
  email      text not null check (char_length(email) between 3 and 200),
  message    text not null check (char_length(message) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.inquiries enable row level security;

-- 許可: サイトを見に来た人は、問い合わせを「書き込む」ことだけできる
-- 「見る」許可は出していないので、他の人の問い合わせは読めない
create policy "誰でも問い合わせを送れる"
  on public.inquiries for insert
  to anon, authenticated
  with check (true);

grant insert on public.inquiries to anon, authenticated;
